using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCPlayWithMe.OpenPlatform.Model.LazadaApp.LazadaProduct
{
    public class LazadaCreateProductResponseBody : CommonLazadaResponseHTTP
    {
        public LazadaCreateProductData data { get; set; }
    }

    public class LazadaCreateProductData
    {
        // The ID of this product,which is not unique in different country
        public long item_id { get; set; }

        public List<LazadaCreateProductSku> sku_list { get; set; }

        // The status of product created, including Active, InActive, and Pending QC.
        // if a product is in Pending status, it needs to be reviewed and will be processed within 24 hours.
        public string item_status { get; set; }
    }

    public class LazadaCreateProductSku
    {
        // The SellerSku that is defined in seller
        public string seller_sku { get; set; }

        // The ShopSku that is generated by the system,which is unique in different country
        public string shop_sku { get; set; }

        // The SKU ID that is generated by the system,which is unique in different country
        public long sku_id { get; set; }
    }
}